/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Зарегистрировать спортсмена и войти
         * @description Роль всегда athlete. Email уникален без учёта регистра. Выдаёт JWT на 24 часа в cookie.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Войти
         * @description Неверная пара email/пароль возвращает 401 с code INVALID_CREDENTIALS. Выдаёт JWT на 24 часа в cookie.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Выйти */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Текущий пользователь */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Мой профиль */
        get: operations["getMyProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Обновить мой профиль
         * @description Только athlete. disciplineIds — полный новый набор без дублей; все ID должны существовать.
         */
        patch: operations["updateMyProfile"];
        trace?: never;
    };
    "/disciplines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список дисциплин */
        get: operations["listDisciplines"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Каталог соревнований
         * @description Публично видны только published/completed. Организатор дополнительно видит draft через отдельный фильтр status=draft; для остальных draft возвращает 403.
         */
        get: operations["listCompetitions"];
        put?: never;
        /**
         * Создать черновик соревнования
         * @description Только organizer. registrationDeadline <= startsAt < endsAt. Начальный status=draft.
         */
        post: operations["createCompetition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competitions/{competitionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Карточка соревнования
         * @description Draft доступен только organizer. Остальным для draft — 404.
         */
        get: operations["getCompetition"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Изменить черновик соревнования */
        patch: operations["updateCompetition"];
        trace?: never;
    };
    "/competitions/{competitionId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Открыть регистрацию
         * @description Только draft; дедлайн должен быть в будущем. Повторный вызов — 409.
         */
        post: operations["publishCompetition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competitions/{competitionId}/registrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Подать заявку
         * @description Только athlete; соревнование published; now < registrationDeadline. Повторная заявка — 409 ALREADY_REGISTERED.
         */
        post: operations["createRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/registrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Мои заявки */
        get: operations["listMyRegistrations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competitions/{competitionId}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Участники соревнования
         * @description Только organizer.
         */
        get: operations["listParticipants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competitions/{competitionId}/results/{registrationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Создать или заменить черновик результата
         * @description Только organizer. Заявка должна принадлежать этому соревнованию. Допустимо только status=published; повторный PUT до публикации заменяет черновик.
         */
        put: operations["upsertResultDraft"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competitions/{competitionId}/results/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Черновики результатов
         * @description Только organizer. Не включает опубликованные результаты.
         */
        get: operations["listResultDrafts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competitions/{competitionId}/results/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Опубликовать все черновики
         * @description Только organizer. Требуется >=1 черновик. Одна транзакция публикует все черновики и завершает соревнование. Повторный вызов — 409 ALREADY_COMPLETED.
         */
        post: operations["publishResults"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competitions/{competitionId}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Публичные результаты соревнования
         * @description Только опубликованные результаты; draft соревнование для публики даёт 404.
         */
        get: operations["listCompetitionResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Мои опубликованные результаты */
        get: operations["listMyResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Общий рейтинг
         * @description Только опубликованные результаты. rank = 1 + число спортсменов с большим числом баллов; ничьи делят место. Пустой рейтинг — items=[],total=0.
         */
        get: operations["getRatings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/rating": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Моя позиция
         * @description Если результатов нет, points=0, resultsCount=0, rank=null.
         */
        get: operations["getMyRating"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список новостей */
        get: operations["listNews"];
        put?: never;
        /** Опубликовать новость */
        post: operations["createNews"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/news/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Открыть новость */
        get: operations["getNews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Изменить новость */
        patch: operations["updateNews"];
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список документов */
        get: operations["listDocuments"];
        put?: never;
        /** Опубликовать ссылку на документ */
        post: operations["createDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Изменить документ */
        patch: operations["updateDocument"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description Stable machine-readable error code */
            code: string;
            /** @description Human-readable Russian message */
            message: string;
            /** @description Optional field errors */
            fields?: {
                [key: string]: string;
            };
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            /** @enum {string} */
            role: "athlete" | "organizer";
            /** Format: date-time */
            createdAt: string;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            fullName: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        Discipline: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        Profile: {
            user: components["schemas"]["User"];
            fullName: string;
            education: string | null;
            locality: string | null;
            disciplineIds: string[];
        };
        ProfilePatch: {
            fullName?: string;
            education?: string | null;
            locality?: string | null;
            disciplineIds?: string[];
        };
        CompetitionCreate: {
            title: string;
            /** Format: uuid */
            disciplineId: string;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            /** Format: date-time */
            registrationDeadline: string;
            /** @enum {string} */
            format: "online" | "offline";
            description: string;
        };
        CompetitionPatch: {
            title?: string;
            /** Format: uuid */
            disciplineId?: string;
            /** Format: date-time */
            startsAt?: string;
            /** Format: date-time */
            endsAt?: string;
            /** Format: date-time */
            registrationDeadline?: string;
            /** @enum {string} */
            format?: "online" | "offline";
            description?: string;
        };
        Competition: {
            /** Format: uuid */
            id: string;
            title: string;
            discipline: components["schemas"]["Discipline"];
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            /** Format: date-time */
            registrationDeadline: string;
            /** @enum {string} */
            format: "online" | "offline";
            description: string;
            /** @enum {string} */
            status: "draft" | "published" | "completed";
            registrationOpen: boolean;
            /** Format: uuid */
            viewerRegistrationId: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        CompetitionPage: {
            items: components["schemas"]["Competition"][];
            page: number;
            pageSize: number;
            total: number;
        };
        Registration: {
            /** Format: uuid */
            id: string;
            competition: components["schemas"]["Competition"];
            /** Format: uuid */
            athleteId: string;
            /** Format: date-time */
            createdAt: string;
        };
        RegistrationPage: {
            items: components["schemas"]["Registration"][];
            page: number;
            pageSize: number;
            total: number;
        };
        Participant: {
            /** Format: uuid */
            registrationId: string;
            /** Format: uuid */
            athleteId: string;
            fullName: string;
            education: string | null;
            locality: string | null;
            /** Format: date-time */
            registeredAt: string;
        };
        ParticipantPage: {
            items: components["schemas"]["Participant"][];
            page: number;
            pageSize: number;
            total: number;
        };
        ResultDraftRequest: {
            place: number;
            scoreText?: string | null;
        };
        ResultDraft: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            registrationId: string;
            /** Format: uuid */
            competitionId: string;
            /** Format: uuid */
            athleteId: string;
            fullName: string;
            place: number;
            scoreText: string | null;
            /** @enum {string} */
            status: "draft";
            /** Format: date-time */
            updatedAt: string;
        };
        ResultDraftPage: {
            items: components["schemas"]["ResultDraft"][];
            page: number;
            pageSize: number;
            total: number;
        };
        Result: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            registrationId: string;
            /** Format: uuid */
            competitionId: string;
            /** Format: uuid */
            athleteId: string;
            fullName: string;
            place: number;
            scoreText: string | null;
            /** @enum {integer} */
            points: 100 | 70 | 50 | 20;
            /** Format: date-time */
            publishedAt: string;
        };
        ResultPage: {
            items: components["schemas"]["Result"][];
            page: number;
            pageSize: number;
            total: number;
        };
        PublishResultsResponse: {
            /** Format: uuid */
            competitionId: string;
            /** @enum {string} */
            status: "completed";
            publishedCount: number;
            /** Format: date-time */
            publishedAt: string;
        };
        RatingRow: {
            /** Format: uuid */
            athleteId: string;
            fullName: string;
            points: number;
            rank: number;
            resultsCount: number;
        };
        Rating: {
            /** Format: uuid */
            disciplineId: string | null;
            formula: string;
            items: components["schemas"]["RatingRow"][];
            page: number;
            pageSize: number;
            total: number;
        };
        MyRating: {
            /** Format: uuid */
            athleteId: string;
            /** Format: uuid */
            disciplineId: string | null;
            points: number;
            rank: number | null;
            resultsCount: number;
        };
        NewsCreate: {
            title: string;
            body: string;
        };
        NewsPatch: {
            title?: string;
            body?: string;
        };
        News: {
            /** Format: uuid */
            id: string;
            title: string;
            body: string;
            /** Format: uuid */
            authorId: string;
            /** Format: date-time */
            publishedAt: string;
        };
        NewsPage: {
            items: components["schemas"]["News"][];
            page: number;
            pageSize: number;
            total: number;
        };
        DocumentCreate: {
            title: string;
            category: string;
            /** Format: uri */
            fileUrl: string;
        };
        DocumentPatch: {
            title?: string;
            category?: string;
            /** Format: uri */
            fileUrl?: string;
        };
        Document: {
            /** Format: uuid */
            id: string;
            title: string;
            category: string;
            /** Format: uri */
            fileUrl: string;
            /** Format: uuid */
            authorId: string;
            /** Format: date-time */
            publishedAt: string;
        };
        DocumentPage: {
            items: components["schemas"]["Document"][];
            page: number;
            pageSize: number;
            total: number;
        };
    };
    responses: {
        /** @description Некорректный запрос */
        400: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "BAD_REQUEST",
                 *       "message": "Некорректный запрос"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Нет действующего JWT */
        401: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "UNAUTHENTICATED",
                 *       "message": "Нет действующего JWT"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Недостаточно прав или неверный/отсутствующий Origin */
        403: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "FORBIDDEN",
                 *       "message": "Недостаточно прав или неверный/отсутствующий Origin"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Ресурс не найден */
        404: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "NOT_FOUND",
                 *       "message": "Ресурс не найден"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Конфликт состояния или уникальности */
        409: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "CONFLICT",
                 *       "message": "Конфликт состояния или уникальности"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Ошибка полей */
        422: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "VALIDATION_ERROR",
                 *       "message": "Ошибка полей"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Успех */
            201: {
                headers: {
                    /** @description tsf_access=<JWT>; HttpOnly; SameSite=Lax; Secure в production; Path=/api/v1; Max-Age=86400 */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            403: components["responses"]["403"];
            409: components["responses"]["409"];
            422: components["responses"]["422"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    /** @description tsf_access=<JWT>; HttpOnly; SameSite=Lax; Secure в production; Path=/api/v1; Max-Age=86400 */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            422: components["responses"]["422"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cookie очищена. Уже выданный JWT нельзя отозвать до exp. */
            204: {
                headers: {
                    /** @description tsf_access=; HttpOnly; SameSite=Lax; Secure в production; Path=/api/v1; Max-Age=0 */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["403"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["401"];
        };
    };
    getMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
        };
    };
    updateMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfilePatch"];
            };
        };
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            422: components["responses"]["422"];
        };
    };
    listDisciplines: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список по имени */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Discipline"][];
                };
            };
        };
    };
    listCompetitions: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                disciplineId?: string;
                status?: "draft" | "published" | "completed";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitionPage"];
                };
            };
            403: components["responses"]["403"];
            422: components["responses"]["422"];
        };
    };
    createCompetition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompetitionCreate"];
            };
        };
        responses: {
            /** @description Успех */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Competition"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            422: components["responses"]["422"];
        };
    };
    getCompetition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                competitionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Competition"];
                };
            };
            404: components["responses"]["404"];
        };
    };
    updateCompetition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                competitionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompetitionPatch"];
            };
        };
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Competition"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
            422: components["responses"]["422"];
        };
    };
    publishCompetition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                competitionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Competition"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
            422: components["responses"]["422"];
        };
    };
    createRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                competitionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Registration"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
        };
    };
    listMyRegistrations: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationPage"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
        };
    };
    listParticipants: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path: {
                competitionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantPage"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
        };
    };
    upsertResultDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                competitionId: string;
                registrationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResultDraftRequest"];
            };
        };
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultDraft"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
            422: components["responses"]["422"];
        };
    };
    listResultDrafts: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path: {
                competitionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultDraftPage"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
        };
    };
    publishResults: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                competitionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishResultsResponse"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
        };
    };
    listCompetitionResults: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path: {
                competitionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultPage"];
                };
            };
            404: components["responses"]["404"];
        };
    };
    listMyResults: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultPage"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
        };
    };
    getRatings: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                disciplineId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rating"];
                };
            };
            422: components["responses"]["422"];
        };
    };
    getMyRating: {
        parameters: {
            query?: {
                disciplineId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyRating"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            422: components["responses"]["422"];
        };
    };
    listNews: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsPage"];
                };
            };
        };
    };
    createNews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewsCreate"];
            };
        };
        responses: {
            /** @description Успех */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["News"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            422: components["responses"]["422"];
        };
    };
    getNews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["News"];
                };
            };
            404: components["responses"]["404"];
        };
    };
    updateNews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewsPatch"];
            };
        };
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["News"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            422: components["responses"]["422"];
        };
    };
    listDocuments: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                category?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentPage"];
                };
            };
        };
    };
    createDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentCreate"];
            };
        };
        responses: {
            /** @description Успех */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            422: components["responses"]["422"];
        };
    };
    updateDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentPatch"];
            };
        };
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            422: components["responses"]["422"];
        };
    };
}
