/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Зарегистрировать спортсмена и войти
         * @description Роль всегда athlete. Email уникален без учёта регистра. Выдаёт JWT на 24 часа в cookie.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Войти
         * @description Неверная пара email/пароль возвращает 401 с code INVALID_CREDENTIALS. Выдаёт JWT на 24 часа в cookie.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Выйти */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Текущий пользователь */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Мой профиль */
        get: operations["getMyProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Обновить мой профиль
         * @description Только athlete. disciplineIds — полный новый набор без дублей; все ID должны существовать.
         */
        patch: operations["updateMyProfile"];
        trace?: never;
    };
    "/disciplines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список дисциплин */
        get: operations["listDisciplines"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Каталог соревнований
         * @description Публично видны только published/completed. Организатор дополнительно видит draft через отдельный фильтр status=draft; для остальных draft возвращает 403.
         */
        get: operations["listCompetitions"];
        put?: never;
        /**
         * Создать черновик соревнования
         * @description Только organizer. registrationDeadline <= startsAt < endsAt. Начальный status=draft.
         */
        post: operations["createCompetition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competitions/{competitionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Карточка соревнования
         * @description Draft доступен только organizer. Остальным для draft — 404.
         */
        get: operations["getCompetition"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Изменить черновик соревнования */
        patch: operations["updateCompetition"];
        trace?: never;
    };
    "/competitions/{competitionId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Открыть регистрацию
         * @description Только draft; дедлайн должен быть в будущем. Повторный вызов — 409.
         */
        post: operations["publishCompetition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competitions/{competitionId}/registrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Подать заявку
         * @description Только athlete; соревнование published; now < registrationDeadline. Повторная заявка — 409 ALREADY_REGISTERED.
         */
        post: operations["createRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/registrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Мои заявки */
        get: operations["listMyRegistrations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competitions/{competitionId}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Участники соревнования
         * @description Только organizer.
         */
        get: operations["listParticipants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competitions/{competitionId}/results/{registrationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Создать или заменить черновик результата
         * @description Только organizer. Заявка должна принадлежать этому соревнованию. Допустимо только status=published; повторный PUT до публикации заменяет черновик.
         */
        put: operations["upsertResultDraft"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competitions/{competitionId}/results/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Черновики результатов
         * @description Только organizer. Не включает опубликованные результаты.
         */
        get: operations["listResultDrafts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competitions/{competitionId}/results/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Опубликовать все черновики
         * @description Только organizer. Требуется >=1 черновик. Одна транзакция публикует все черновики и завершает соревнование. Повторный вызов — 409 ALREADY_COMPLETED.
         */
        post: operations["publishResults"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competitions/{competitionId}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Публичные результаты соревнования
         * @description Только опубликованные результаты; draft соревнование для публики даёт 404.
         */
        get: operations["listCompetitionResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Мои опубликованные результаты */
        get: operations["listMyResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Общий рейтинг
         * @description Только опубликованные результаты. rank = 1 + число спортсменов с большим числом баллов; ничьи делят место. Пустой рейтинг — items=[],total=0.
         */
        get: operations["getRatings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/rating": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Моя позиция
         * @description Если результатов нет, points=0, resultsCount=0, rank=null.
         */
        get: operations["getMyRating"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список новостей */
        get: operations["listNews"];
        put?: never;
        /** Опубликовать новость */
        post: operations["createNews"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/news/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Открыть новость */
        get: operations["getNews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Изменить новость */
        patch: operations["updateNews"];
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список документов */
        get: operations["listDocuments"];
        put?: never;
        /** Опубликовать ссылку на документ */
        post: operations["createDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Изменить документ */
        patch: operations["updateDocument"];
        trace?: never;
    };
    "/competitions/{competitionId}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список заданий
         * @description Черновик виден только организатору; опубликованное/завершённое соревнование — всем.
         */
        get: operations["listTasks"];
        put?: never;
        /**
         * Добавить задание
         * @description Только organizer, только пока соревнование в статусе draft.
         */
        post: operations["createTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competitions/{competitionId}/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Удалить задание
         * @description Только organizer, только пока соревнование в статусе draft.
         */
        delete: operations["deleteTask"];
        options?: never;
        head?: never;
        /**
         * Изменить задание
         * @description Только organizer, только пока соревнование в статусе draft. Нужно хотя бы одно поле.
         */
        patch: operations["updateTask"];
        trace?: never;
    };
    "/competitions/{competitionId}/tasks/{taskId}/submission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Отправить или заменить решение
         * @description Только athlete со своей заявкой на это соревнование. Доступно, пока соревнование published и текущее время в [startsAt, endsAt). Повторный вызов заменяет решение и сбрасывает оценку.
         */
        put: operations["submitSolution"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competitions/{competitionId}/my-submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Мои решения по соревнованию
         * @description Только athlete. Пустой список, если заявки нет или решений ещё нет.
         */
        get: operations["listMySubmissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competitions/{competitionId}/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Очередь решений на проверку
         * @description Только organizer. Решения по всем заданиям соревнования с именем спортсмена.
         */
        get: operations["listSubmissionsForGrading"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competitions/{competitionId}/submissions/{submissionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Оценить решение
         * @description Только organizer. Балл должен быть от 0 до maxScore задания.
         */
        patch: operations["gradeSubmission"];
        trace?: never;
    };
    "/competitions/{competitionId}/finish-contest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Завершить контест
         * @description Только organizer. Требует хотя бы одно задание и отсутствие непроверенных решений. Считает сумму баллов по каждой заявке и публикует результат существующим механизмом Results/Rating одной операцией.
         */
        post: operations["finishContest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competitions/{competitionId}/registrations/{registrationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Убрать участника
         * @description Только organizer. Нельзя убрать участника завершённого соревнования.
         */
        delete: operations["removeRegistration"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competitions/{competitionId}/standings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Таблица результатов по заданиям
         * @description Публично для published/completed соревнований с заданиями; черновик виден только organizer. Баллы по каждому заданию, как в Codeforces.
         */
        get: operations["getStandings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Каталог прав
         * @description Группированный справочник прав для конструктора роли. Только roles.manage.
         */
        get: operations["listPermissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список ролей
         * @description Все роли с их правами. Только roles.manage.
         */
        get: operations["listRoles"];
        put?: never;
        /**
         * Создать роль
         * @description Создаёт динамическую роль с набором прав. Только roles.manage. Системные роли менять нельзя.
         */
        post: operations["createRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/roles/{roleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Удалить роль
         * @description Только динамические роли без назначенных пользователей. Системная — 403 ROLE_SYSTEM, назначенная — 409 ROLE_IN_USE.
         */
        delete: operations["deleteRole"];
        options?: never;
        head?: never;
        /**
         * Изменить роль
         * @description Меняет имя/описание динамической роли. Только roles.manage; системные роли — 403 ROLE_SYSTEM.
         */
        patch: operations["updateRole"];
        trace?: never;
    };
    "/admin/roles/{roleId}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Назначить права роли
         * @description Полностью заменяет набор прав динамической роли. Только roles.manage; системные роли — 403 ROLE_SYSTEM.
         */
        put: operations["updateRolePermissions"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список пользователей
         * @description Пользователи с ролью и именем (из профиля спортсмена, если есть). Только users.manage.
         */
        get: operations["listAdminUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{userId}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Назначить роль пользователю
         * @description Меняет роль пользователя. Изменение прав вступит в силу после следующего входа (JWT до 24ч). Только users.manage.
         */
        put: operations["assignUserRole"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description Stable machine-readable error code */
            code: string;
            /** @description Human-readable Russian message */
            message: string;
            /** @description Optional field errors */
            fields?: {
                [key: string]: string;
            };
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            /**
             * @description Имя роли пользователя: системные athlete/organizer/master-admin или динамическая роль master admin
             * @enum {string}
             */
            role: "athlete" | "organizer";
            /** Format: date-time */
            createdAt: string;
            /** @description Права текущей роли, например news.create */
            permissions: string[];
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            fullName: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        Discipline: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        Profile: {
            user: components["schemas"]["User"];
            fullName: string;
            education: string | null;
            locality: string | null;
            disciplineIds: string[];
        };
        ProfilePatch: {
            fullName?: string;
            education?: string | null;
            locality?: string | null;
            disciplineIds?: string[];
        };
        CompetitionCreate: {
            title: string;
            /** Format: uuid */
            disciplineId: string;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            /** Format: date-time */
            registrationDeadline: string;
            /** @enum {string} */
            format: "online" | "offline";
            description: string;
        };
        CompetitionPatch: {
            title?: string;
            /** Format: uuid */
            disciplineId?: string;
            /** Format: date-time */
            startsAt?: string;
            /** Format: date-time */
            endsAt?: string;
            /** Format: date-time */
            registrationDeadline?: string;
            /** @enum {string} */
            format?: "online" | "offline";
            description?: string;
        };
        Competition: {
            /** Format: uuid */
            id: string;
            title: string;
            discipline: components["schemas"]["Discipline"];
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            /** Format: date-time */
            registrationDeadline: string;
            /** @enum {string} */
            format: "online" | "offline";
            description: string;
            /** @enum {string} */
            status: "draft" | "published" | "completed";
            registrationOpen: boolean;
            /** Format: uuid */
            viewerRegistrationId: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        CompetitionPage: {
            items: components["schemas"]["Competition"][];
            page: number;
            pageSize: number;
            total: number;
        };
        Registration: {
            /** Format: uuid */
            id: string;
            competition: components["schemas"]["Competition"];
            /** Format: uuid */
            athleteId: string;
            /** Format: date-time */
            createdAt: string;
        };
        RegistrationPage: {
            items: components["schemas"]["Registration"][];
            page: number;
            pageSize: number;
            total: number;
        };
        Participant: {
            /** Format: uuid */
            registrationId: string;
            /** Format: uuid */
            athleteId: string;
            fullName: string;
            education: string | null;
            locality: string | null;
            /** Format: date-time */
            registeredAt: string;
        };
        ParticipantPage: {
            items: components["schemas"]["Participant"][];
            page: number;
            pageSize: number;
            total: number;
        };
        ResultDraftRequest: {
            place: number;
            scoreText?: string | null;
        };
        ResultDraft: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            registrationId: string;
            /** Format: uuid */
            competitionId: string;
            /** Format: uuid */
            athleteId: string;
            fullName: string;
            place: number;
            scoreText: string | null;
            /** @enum {string} */
            status: "draft";
            /** Format: date-time */
            updatedAt: string;
        };
        ResultDraftPage: {
            items: components["schemas"]["ResultDraft"][];
            page: number;
            pageSize: number;
            total: number;
        };
        Result: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            registrationId: string;
            /** Format: uuid */
            competitionId: string;
            /** Format: uuid */
            athleteId: string;
            fullName: string;
            place: number;
            scoreText: string | null;
            /** @enum {integer} */
            points: 100 | 70 | 50 | 20;
            /** Format: date-time */
            publishedAt: string;
        };
        ResultPage: {
            items: components["schemas"]["Result"][];
            page: number;
            pageSize: number;
            total: number;
        };
        PublishResultsResponse: {
            /** Format: uuid */
            competitionId: string;
            /** @enum {string} */
            status: "completed";
            publishedCount: number;
            /** Format: date-time */
            publishedAt: string;
        };
        RatingRow: {
            /** Format: uuid */
            athleteId: string;
            fullName: string;
            points: number;
            rank: number;
            resultsCount: number;
        };
        Rating: {
            /** Format: uuid */
            disciplineId: string | null;
            formula: string;
            items: components["schemas"]["RatingRow"][];
            page: number;
            pageSize: number;
            total: number;
        };
        MyRating: {
            /** Format: uuid */
            athleteId: string;
            /** Format: uuid */
            disciplineId: string | null;
            points: number;
            rank: number | null;
            resultsCount: number;
        };
        NewsCreate: {
            title: string;
            body: string;
        };
        NewsPatch: {
            title?: string;
            body?: string;
        };
        News: {
            /** Format: uuid */
            id: string;
            title: string;
            body: string;
            /** Format: uuid */
            authorId: string;
            /** Format: date-time */
            publishedAt: string;
        };
        NewsPage: {
            items: components["schemas"]["News"][];
            page: number;
            pageSize: number;
            total: number;
        };
        DocumentCreate: {
            title: string;
            category: string;
            /** Format: uri */
            fileUrl: string;
        };
        DocumentPatch: {
            title?: string;
            category?: string;
            /** Format: uri */
            fileUrl?: string;
        };
        Document: {
            /** Format: uuid */
            id: string;
            title: string;
            category: string;
            /** Format: uri */
            fileUrl: string;
            /** Format: uuid */
            authorId: string;
            /** Format: date-time */
            publishedAt: string;
        };
        DocumentPage: {
            items: components["schemas"]["Document"][];
            page: number;
            pageSize: number;
            total: number;
        };
        Task: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            competitionId: string;
            title: string;
            statement: string;
            maxScore: number;
            orderIndex: number;
            /** @enum {string} */
            judgingMode: "manual" | "code";
            timeLimitSeconds: number;
            memoryLimitMb: number;
            visibleTestCount: number;
            testCaseCount: number;
            testCases: components["schemas"]["TestCaseInput"][];
        };
        TaskCreateRequest: {
            title: string;
            statement: string;
            maxScore: number;
            /**
             * @default manual
             * @enum {string}
             */
            judgingMode: "manual" | "code";
            /** @default [] */
            testCases: components["schemas"]["TestCaseInput"][];
            /** @default 15 */
            timeLimitSeconds: number;
            /** @default 128 */
            memoryLimitMb: number;
            /** @default 2 */
            visibleTestCount: number;
        };
        TaskPatchRequest: {
            title?: string;
            statement?: string;
            maxScore?: number;
            /** @enum {string} */
            judgingMode?: "manual" | "code";
            testCases?: components["schemas"]["TestCaseInput"][];
            timeLimitSeconds?: number;
            memoryLimitMb?: number;
            visibleTestCount?: number;
        };
        SubmissionRequest: {
            /** @enum {string} */
            kind: "text" | "link" | "code";
            content: string;
            /** @enum {string|null} */
            language?: "python" | "javascript" | "go" | "java" | "kotlin" | "cpp" | "rust" | null;
        };
        Submission: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            taskId: string;
            /** Format: uuid */
            registrationId: string;
            /** @enum {string} */
            kind: "text" | "link" | "code";
            content: string;
            /** Format: date-time */
            submittedAt: string;
            score: number | null;
            /** Format: date-time */
            gradedAt: string | null;
            language: string | null;
            verdict: string | null;
            failedTestIndex: number | null;
            timeMs: number | null;
            memoryKb: number | null;
            testResults: components["schemas"]["TestResult"][];
            judgeMessage: string | null;
        };
        SubmissionForGrading: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            taskId: string;
            /** Format: uuid */
            registrationId: string;
            /** @enum {string} */
            kind: "text" | "link" | "code";
            content: string;
            /** Format: date-time */
            submittedAt: string;
            score: number | null;
            /** Format: date-time */
            gradedAt: string | null;
            taskTitle: string;
            taskMaxScore: number;
            athleteFullName: string;
            language: string | null;
            verdict: string | null;
            failedTestIndex: number | null;
            timeMs: number | null;
            memoryKb: number | null;
            testResults: components["schemas"]["TestResult"][];
            judgeMessage: string | null;
        };
        GradeRequest: {
            score: number;
        };
        FinishContestResponse: {
            /** Format: uuid */
            competitionId: string;
            /** @enum {string} */
            status: "completed";
            publishedCount: number;
            /** Format: date-time */
            publishedAt: string;
        };
        StandingsTask: {
            /** Format: uuid */
            id: string;
            title: string;
            maxScore: number;
        };
        StandingsRow: {
            /** Format: uuid */
            registrationId: string;
            fullName: string;
            place: number;
            totalScore: number;
            taskScores: (number | null)[];
        };
        Standings: {
            maxTotalScore: number;
            tasks: components["schemas"]["StandingsTask"][];
            items: components["schemas"]["StandingsRow"][];
        };
        PermissionGroup: {
            section: string;
            label: string;
            codes: string[];
        };
        Role: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string | null;
            isSystem: boolean;
            permissions: string[];
            /** Format: date-time */
            createdAt: string;
        };
        RoleCreate: {
            name: string;
            description?: string | null;
            permissions?: string[];
        };
        RolePatch: {
            name?: string;
            description?: string | null;
        };
        PermissionsUpdate: {
            permissions: string[];
        };
        AssignRoleRequest: {
            /** Format: uuid */
            roleId: string;
        };
        AdminUser: {
            /** Format: uuid */
            id: string;
            email: string;
            fullName: string | null;
            /** Format: uuid */
            roleId: string;
            roleName: string;
            /** Format: date-time */
            createdAt: string;
        };
        AdminUserPage: {
            items: components["schemas"]["AdminUser"][];
            page: number;
            pageSize: number;
            total: number;
        };
        TestCaseInput: {
            input: string;
            expectedOutput: string;
        };
        TestResult: {
            index: number;
            verdict: string;
            timeMs: number | null;
            memoryKb: number | null;
            actualOutput: string | null;
            stderr: string | null;
        };
    };
    responses: {
        /** @description Некорректный запрос */
        400: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "BAD_REQUEST",
                 *       "message": "Некорректный запрос"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Нет действующего JWT */
        401: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "UNAUTHENTICATED",
                 *       "message": "Нет действующего JWT"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Недостаточно прав или неверный/отсутствующий Origin */
        403: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "FORBIDDEN",
                 *       "message": "Недостаточно прав или неверный/отсутствующий Origin"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Ресурс не найден */
        404: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "NOT_FOUND",
                 *       "message": "Ресурс не найден"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Конфликт состояния или уникальности */
        409: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "CONFLICT",
                 *       "message": "Конфликт состояния или уникальности"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Ошибка полей */
        422: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "VALIDATION_ERROR",
                 *       "message": "Ошибка полей"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Успех */
            201: {
                headers: {
                    /** @description tsf_access=<JWT>; HttpOnly; SameSite=Lax; Secure в production; Path=/api/v1; Max-Age=86400 */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            403: components["responses"]["403"];
            409: components["responses"]["409"];
            422: components["responses"]["422"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    /** @description tsf_access=<JWT>; HttpOnly; SameSite=Lax; Secure в production; Path=/api/v1; Max-Age=86400 */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            422: components["responses"]["422"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cookie очищена. Уже выданный JWT нельзя отозвать до exp. */
            204: {
                headers: {
                    /** @description tsf_access=; HttpOnly; SameSite=Lax; Secure в production; Path=/api/v1; Max-Age=0 */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["403"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["401"];
        };
    };
    getMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
        };
    };
    updateMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfilePatch"];
            };
        };
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            422: components["responses"]["422"];
        };
    };
    listDisciplines: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список по имени */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Discipline"][];
                };
            };
        };
    };
    listCompetitions: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                disciplineId?: string;
                status?: "draft" | "published" | "completed";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitionPage"];
                };
            };
            403: components["responses"]["403"];
            422: components["responses"]["422"];
        };
    };
    createCompetition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompetitionCreate"];
            };
        };
        responses: {
            /** @description Успех */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Competition"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            422: components["responses"]["422"];
        };
    };
    getCompetition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                competitionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Competition"];
                };
            };
            404: components["responses"]["404"];
        };
    };
    updateCompetition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                competitionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompetitionPatch"];
            };
        };
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Competition"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
            422: components["responses"]["422"];
        };
    };
    publishCompetition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                competitionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Competition"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
            422: components["responses"]["422"];
        };
    };
    createRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                competitionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Registration"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
        };
    };
    listMyRegistrations: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationPage"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
        };
    };
    listParticipants: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path: {
                competitionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantPage"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
        };
    };
    upsertResultDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                competitionId: string;
                registrationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResultDraftRequest"];
            };
        };
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultDraft"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
            422: components["responses"]["422"];
        };
    };
    listResultDrafts: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path: {
                competitionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultDraftPage"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
        };
    };
    publishResults: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                competitionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishResultsResponse"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
        };
    };
    listCompetitionResults: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path: {
                competitionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultPage"];
                };
            };
            404: components["responses"]["404"];
        };
    };
    listMyResults: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultPage"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
        };
    };
    getRatings: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                disciplineId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rating"];
                };
            };
            422: components["responses"]["422"];
        };
    };
    getMyRating: {
        parameters: {
            query?: {
                disciplineId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyRating"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            422: components["responses"]["422"];
        };
    };
    listNews: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsPage"];
                };
            };
        };
    };
    createNews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewsCreate"];
            };
        };
        responses: {
            /** @description Успех */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["News"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            422: components["responses"]["422"];
        };
    };
    getNews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["News"];
                };
            };
            404: components["responses"]["404"];
        };
    };
    updateNews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewsPatch"];
            };
        };
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["News"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            422: components["responses"]["422"];
        };
    };
    listDocuments: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                category?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentPage"];
                };
            };
        };
    };
    createDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentCreate"];
            };
        };
        responses: {
            /** @description Успех */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            422: components["responses"]["422"];
        };
    };
    updateDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentPatch"];
            };
        };
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            422: components["responses"]["422"];
        };
    };
    listTasks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                competitionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"][];
                };
            };
            401: components["responses"]["401"];
            404: components["responses"]["404"];
        };
    };
    createTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                competitionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreateRequest"];
            };
        };
        responses: {
            /** @description Создано */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
            422: components["responses"]["422"];
        };
    };
    deleteTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                competitionId: string;
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
        };
    };
    updateTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                competitionId: string;
                taskId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskPatchRequest"];
            };
        };
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
            422: components["responses"]["422"];
        };
    };
    submitSolution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                competitionId: string;
                taskId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmissionRequest"];
            };
        };
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Submission"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
            422: components["responses"]["422"];
        };
    };
    listMySubmissions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                competitionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Submission"][];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
        };
    };
    listSubmissionsForGrading: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                competitionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionForGrading"][];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
        };
    };
    gradeSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                competitionId: string;
                submissionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GradeRequest"];
            };
        };
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Submission"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            422: components["responses"]["422"];
        };
    };
    finishContest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                competitionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinishContestResponse"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
        };
    };
    removeRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                competitionId: string;
                registrationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
        };
    };
    getStandings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                competitionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Standings"];
                };
            };
            401: components["responses"]["401"];
            404: components["responses"]["404"];
        };
    };
    listPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionGroup"][];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
        };
    };
    listRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"][];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
        };
    };
    createRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleCreate"];
            };
        };
        responses: {
            /** @description Успех */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            409: components["responses"]["409"];
            422: components["responses"]["422"];
        };
    };
    deleteRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
        };
    };
    updateRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RolePatch"];
            };
        };
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
            422: components["responses"]["422"];
        };
    };
    updateRolePermissions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PermissionsUpdate"];
            };
        };
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            422: components["responses"]["422"];
        };
    };
    listAdminUsers: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserPage"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
        };
    };
    assignUserRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignRoleRequest"];
            };
        };
        responses: {
            /** @description Успех */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
            401: components["responses"]["401"];
            403: components["responses"]["403"];
            404: components["responses"]["404"];
            422: components["responses"]["422"];
        };
    };
}
